### ISSUE TITLE
maxLines bug

### ISSUE THREAD

**Issue by gaoyong06** [fayeed/flutter_parsed_text#12]
if **maxLines** set **null** it's mean  **unlimited**  in flutter

> ~/flutter/packages/flutter/lib/src/widgets/basic.dart

`  /// The [maxLines] property may be null (and indeed defaults to null), but if
  /// it is not null, it must be greater than zero.`

`properties.add(IntProperty('maxLines', maxLines, ifNull: 'unlimited'));`

but in ParsedText, write like **maxLines: null** it's show 1 line
bug ?

`ParsedText(
              alignment: TextAlign.start,
              maxLines: null,
              overflow: TextOverflow.ellipsis,
              text:`

**Comment by fayeed** [comment]
@gaoyong06 I guess its a bug I will take a look at it.

**Comment by fayeed** [comment]
@gaoyong06 It works as expected, So I am closing this issue.
