### ISSUE TITLE
Add option to also use SelectableText?

### ISSUE THREAD

**Issue by gliheng** [fayeed/flutter_parsed_text#14]
Text rendered by this widget use RichText and is not selectable. Can you add an option to use Selectable.rich widget? That may make text selectable.

**Comment by gliheng** [comment]
Hi, I added selectable option in this PR.  https://github.com/fayeed/flutter_parsed_text/pull/15 Works great so far.

**Comment by fayeed** [comment]
@gliheng Thanks for the PR. I have updated the package to `v1.2.4`.
