### ISSUE TITLE
Can click event add style response?

### ISSUE THREAD

**Issue by HeebeLee** [fayeed/flutter_parsed_text#16]
Thank you for creating this package, I really like it.
I often use it to do some rich text work, it works very well. But one thing, we have some rich text that needs to be clicked, and these clicks need to match the material style to give users visual feedback. So we need to change the style of the text when we click.

So can such a function be added?

thx.

**Comment by fayeed** [comment]
Maybe a builder property in `MatchText` would be good to solve this. I will let you know once I add that.

**Comment by prsolucoes** [comment]
+1

**Comment by fayeed** [comment]
@HeebeLee @paulo-coutinho  You can add your own widget using `renderWidget` for `MatchText` available in v2.0.1.
