### ISSUE TITLE
Extending to TextField

### ISSUE THREAD

**Issue by dheeraj2dj** [fayeed/flutter_parsed_text#22]
Thanks for developing this is a great package!

I was wondering if it's possible to add a `ParsedTextField` widget to this package, to cater a multiline TextField to have such styling.
I am a newbie to flutter. If I can gather some information around it, will contribute.

Just putting out the idea here for now.

**Comment by fayeed** [comment]
There is a supporting package for this you check it here: https://github.com/fayeed/flutter_mentions
