### ISSUE TITLE
if onTap is not provided, the TextSpan should't react to gestures

### ISSUE THREAD

**Issue by alectogeek** [fayeed/flutter_parsed_text#24]
Now it is not possible to work with ParsedText is there is no need to react to user clicks and onTap is null. Moreover, I cannot wrap ParsedText with another GestureDetector and handle other user gestures (Had to wrap with IgnorePointer)

**Comment by fayeed** [comment]
@alectogeek Are you facing any issue while not setting the `onTap` function?

The `ParsedText` Widget is the `RichText` widget that could be the problem.

**Comment by alectogeek** [comment]
@fayeed Yeah, it throws an exception if onTap is not set. Moreover, parent GestureDetectors can't listen to gesture events on top of ParsedText

**Comment by fayeed** [comment]
@alectogeek This has been fixed in v1.2.5
