### ISSUE TITLE
onTap uses matchText instead of result['value'] when using renderText

### ISSUE THREAD

**Issue by magnusrp0808** [fayeed/flutter_parsed_text#40]
According to the readme file in the renderText function you're supposed to return a Map with 'display' and 'value' entries where the 'value' entry is the value used. However, in the current version the 'value' entry is never even used. I can see that it was previously used but this was changed in commit f5051f5. Was this on purpose or just a slight mistake? If it was on purpose then it does not make sense to return a map from renderText since only the 'display' entry is used.

**Comment by michasng** [comment]
I can confirm that this is still an issue. Has this project been abandoned?
