### ISSUE TITLE
The method 'split' was called on null

### ISSUE THREAD

**Issue by liuchuancong** [fayeed/flutter_parsed_text#6]
NoSuchMethodError (NoSuchMethodError: The method 'split' was called on null.
Receiver: null
Tried calling: split("%%%%"))

**Comment by liuchuancong** [comment]
I aways get this problem

**Comment by liuchuancong** [comment]
The following NoSuchMethodError was thrown building ParsedText(dirty)

**Comment by liuchuancong** [comment]
because of i recived null

**Comment by fayeed** [comment]
Can you show some code of what you are doing?

**Comment by liuchuancong** [comment]
sorry,it's my my fault.
