### ISSUE TITLE
Extra space after match

### ISSUE THREAD

**Issue by peekpt** [fayeed/flutter_parsed_text#8]
![Captura de ecrã 2019-09-07, às 23 07 57](https://user-images.githubusercontent.com/222385/64480713-74824380-d1c4-11e9-9bc4-838dff06f7ec.png)

**Comment by peekpt** [comment]
Another question how can I add case insensitive to a pattern? Thank you

**Comment by fayeed** [comment]
You need to use `regexOptions` parameter, by default it sets regex as case sensitive you can set to insensitive like so, you can use it like so:

```dart
ParsedText(
  pattern: "YOUR_PATTERN",
  regexOptions: RegexOptions(
    caseSensitive: false,
  )
)
```

**Comment by fayeed** [comment]
And also make sure you are using version `1.2.2`.

**Comment by peekpt** [comment]
Thank you for adding regexOptions:

The white space is still showing thought.
![Captura de ecrã 2019-09-08, às 09 55 57](https://user-images.githubusercontent.com/222385/64485973-0880f900-d21f-11e9-84a0-7a408aa1a167.png)

Another possible bug:

Empty string pattern (non null) is currently Matching all the text.
For variable patterns like this example, is it possible to return the original unmodified text?

var returningText = ( pattern.isEmpty || pattern == null ) ? matchedText : originalText;

**Comment by fayeed** [comment]
My bad actually changed I changed how the package works in version `1.2.0` and forgot to remove the white spaces from the previous implementation it should work now. Try version `1.2.3`

**Comment by peekpt** [comment]
yes it's working now! Is it possible to fix the empty string?

As you can see I have to make a workaround for this by inserting a unmatchable pattern:
final pattern = query.isNotEmpty ? query : 'sadaaDSADASD';

![Captura de ecrã 2019-09-08, às 11 17 05](https://user-images.githubusercontent.com/222385/64486831-433c5e80-d22a-11e9-8d09-2f24c9a6720d.png)

but if I return an empty string 
final pattern = query.;
![Captura de ecrã 2019-09-08, às 11 15 17](https://user-images.githubusercontent.com/222385/64486812-f789b500-d229-11e9-9cbb-fe9648ea0d4b.png)

**Comment by fayeed** [comment]
Well, actually I was going to give you the same the solution that you came up with. 

Anyway, the reason I think it would be a bad idea to return the original text when the pattern is empty is that how regex work and your case is pretty specific and it would create confusion for others who might except this behavior.

**Comment by peekpt** [comment]
Fair enough ,thank you for your help
